# Generated by Django 5.1.1 on 2024-10-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0003_alter_client_profile_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_profile',
            old_name='cpf',
            new_name='cpf_user',
        ),
    ]
