# Generated by Django 5.1.1 on 2024-10-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0004_rename_cpf_client_profile_cpf_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_profile',
            name='cpf_user',
        ),
        migrations.AddField(
            model_name='client_profile',
            name='cpf',
            field=models.CharField(default='0000000000', max_length=11, verbose_name='CPF'),
        ),
    ]
