# Generated by Django 5.1.1 on 2024-10-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_qtd',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
