# Generated by Django 5.1.1 on 2024-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_quantity_orderitem_quantitative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_qtd',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variation_id',
            field=models.PositiveIntegerField(),
        ),
    ]
